name: cpp-linter
on:
  pull_request:
    branches: [main, master, develop]
    paths: ['**.cpp', '**.h']
  push:
    branches: [main, master, develop]
    paths: ['**.cpp', '**.h']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ... optionally setup build env to create a compilation database

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: 'file'  # Use .clang-format config file. 
          tidy-checks: '' # Use .clang-tidy config file.

      - name: Fail fast?!
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: exit 1
